name: deploy-prod
on: 
  workflow_dispatch:
    inputs:
      ENVIRONMENT_NAME:
        required: true
        type: string
      ECR_REPOSITORY:
        required: true
        type: string           
      BRANCH:
        required: true
        type: string
      # FILE_SYSTEM_ID:
      #   required: true
      #   type: string                
env:
  REGION: 'ap-southeast-2'
concurrency: ${{ github.workflow }}-${{ github.ref }}-pipeline
jobs:
  deploy_prod:
    runs-on: [linux, self-hosted, demo]
    if: github.ref != 'refs/heads/main'
    container:
      image: 'node:20'
    permissions:
      id-token: write
      contents: read
    env:
      ENVIRONMENT_NAME: ${{ inputs.ENVIRONMENT_NAME }}
      ACCOUNT_NAME: 'sandpit1'
      aws_account_id: '722141136946' 
      ECR_REPOSITORY: ${{ inputs.ECR_REPOSITORY }}
      IMAGE_TAG: ${{ inputs.BRANCH }}-${{ github.run_id }}
      FILE_SYSTEM_ID: 'fs-07daaa2a11a487e56'
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ env.aws_account_id }}:role/github-actions-demo
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.REGION }}
      - name: run synth
        run: |
          echo ${ECR_REPOSITORY}
          npm install
          npx cdk destroy --require-approval=never